name: Rebase against original repo

# on: [push]
on:
  schedule:
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        token: ${{ secrets.YOUR_SECRET_NAME }}
    - name: Git configuration
      run: |
        git config user.name "Passw"
        git config user.email "Passw_Passw@163.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git remote -vv
        git branch -vv
    - name: RUN `git pull master -r`
      run: |
        pwd
        git remote add up https://github.com/vim/vim.git
        pwd
        git log --oneline | wc -l
        git log --oneline origin/master..master | wc -l
        git fetch origin --unshallow
        git log --oneline | wc -l
        git pull -r origin master
        git log --oneline | wc -l
        git status
        git remote -vv
        git log --oneline | wc -l
        git fetch up master
        git pull up master -r
        git log --oneline | wc -l
        pwd
        git status
        git push origin HEAD:master --force
        pwd
        git status
